import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileExists } from "./fs.js";
import type { AppliedPatchOperation, AppliedPatchReport } from "./patch-set.js";

export interface ExecutionLog {
  version: 1;
  entries: AppliedPatchReport[];
}

export async function appendExecutionLog(path: string, entry: AppliedPatchReport): Promise<ExecutionLog> {
  const log = await readExecutionLog(path);
  const next: ExecutionLog = {
    version: 1,
    entries: [...log.entries, entry]
  };

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${JSON.stringify(next, null, 2)}\n`, "utf8");

  return next;
}

export function formatTaskChangelog(log: ExecutionLog): string {
  const operations = log.entries.flatMap((entry) => entry.operations);
  const touchedFiles = unique(operations.filter((operation) => operation.status !== "unchanged").map((operation) => operation.path));
  const lineDelta = operations.reduce((total, operation) => total + (operation.lineDelta ?? 0), 0);
  const summary = [
    `- Entries: ${log.entries.length}`,
    `- Applied entries: ${log.entries.filter((entry) => entry.status === "applied").length}`,
    `- Unchanged entries: ${log.entries.filter((entry) => entry.status === "unchanged").length}`,
    touchedFiles.length ? `- Touched files: ${formatInlineList(touchedFiles)}` : "- Touched files: none",
    `- Line delta: ${formatSignedNumber(lineDelta)}`
  ];

  return `# Task Changelog

Generated by DevFlow from \`.devflow/artifacts/execution-log.json\`.

## Summary

${summary.join("\n")}

## Entries

${log.entries.length ? log.entries.map(formatTaskChangelogEntry).join("\n\n") : "- No source-changing task entries recorded."}
`;
}

function formatTaskChangelogEntry(entry: AppliedPatchReport): string {
  const lines = [
    `### ${entry.taskId}`,
    "",
    `- Applied at: ${entry.appliedAt}`,
    `- Status: ${entry.status}`,
    `- Summary: ${entry.summary}`,
    entry.backupManifestPath ? `- Backup: \`${entry.backupManifestPath}\`` : undefined,
    "- Operations:",
    ...entry.operations.map(formatTaskChangelogOperation)
  ].filter((line): line is string => Boolean(line));

  return lines.join("\n");
}

function formatTaskChangelogOperation(operation: AppliedPatchOperation): string {
  const details = [
    operation.status,
    `${operation.bytesWritten} bytes`,
    operation.replacements === undefined ? undefined : `${operation.replacements} replacement(s)`,
    formatLineStats(operation)
  ].filter((value): value is string => Boolean(value));

  return `  - ${operation.type} \`${operation.path}\`: ${details.join(", ")}`;
}

async function readExecutionLog(path: string): Promise<ExecutionLog> {
  if (!(await fileExists(path))) {
    return {
      version: 1,
      entries: []
    };
  }

  return JSON.parse(await readFile(path, "utf8")) as ExecutionLog;
}

function formatLineStats(operation: AppliedPatchOperation): string | undefined {
  if (operation.linesBefore === undefined || operation.linesAfter === undefined || operation.lineDelta === undefined) {
    return undefined;
  }

  return `lines ${operation.linesBefore}->${operation.linesAfter} (${formatSignedNumber(operation.lineDelta)})`;
}

function formatInlineList(values: string[]): string {
  const shown = values.slice(0, 8).map((value) => `\`${value}\``).join(", ");
  const omitted = values.length - 8;

  return omitted > 0 ? `${shown}, and ${omitted} more` : shown;
}

function formatSignedNumber(value: number): string {
  return value > 0 ? `+${value}` : String(value);
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}
