import type { ProjectBrief } from "./brief.js";
import type { ProjectContext } from "./context.js";
import type { AiProvider } from "./provider.js";
import { extractMarkdownSignals } from "./signals.js";

export async function createImplementationPlan(
  context: ProjectContext,
  provider: AiProvider | undefined,
  brief?: ProjectBrief,
  prompt = buildPlannerPrompt(context, brief)
): Promise<string> {
  if (provider) {
    const providerPlan = await provider.completePlan(context, prompt);

    return normalizeProviderPlan(providerPlan, context, brief);
  }

  return createFallbackPlan(context, brief);
}

export function buildPlannerPrompt(context: ProjectContext, brief?: ProjectBrief): string {
  return `Create a frontend implementation plan from the following project context.

The plan must include:
- Summary
- Assumptions
- Implementation phases
- Frontend Delivery Blueprint with these exact subsections:
  - Routes And Navigation
  - Components
  - State And Interaction
  - Data And API Integration
  - Styling And Responsive Rules
  - Test Plan
  - Accessibility Checks
- Test and verification checklist
- Delivery risks

${brief ? `## Structured Project Brief\n\n${JSON.stringify(brief, null, 2)}\n` : ""}

## Requirements (${context.requirementsPath})

${context.requirements}

## UI Notes (${context.uiPath})

${context.ui}

## API Docs (${context.apiPath})

${context.api}
`;
}

function createFallbackPlan(context: ProjectContext, brief?: ProjectBrief): string {
  const requirementSignals = brief?.signals.requirements ?? extractMarkdownSignals(context.requirements);
  const uiSignals = brief?.signals.ui ?? extractMarkdownSignals(context.ui);
  const apiSignals = brief?.signals.api ?? extractMarkdownSignals(context.api);

  return `# Implementation Plan

Generated by DevFlow local fallback planner.

## Summary

Build the project or frontend feature described by the requirements, UI notes, and API documentation. Before implementation, confirm ambiguous product behavior and map the work into small, reviewable tasks.

## Source Documents

- Requirements: \`${context.requirementsPath}\`
- UI notes: \`${context.uiPath}\`
- API docs: \`${context.apiPath}\`

${brief ? formatRequirementDetailsSection(brief) : ""}

${brief ? formatDesignAssetsSection(brief) : ""}

${brief ? formatUiStateChecklistSection(brief) : ""}

${brief ? formatApiContractsSection(brief) : ""}

${brief ? formatApiDataModelsSection(brief) : ""}

${brief ? formatApiOperationalConstraintsSection(brief) : ""}

## Extracted Signals

${brief ? formatStackSection(brief) : ""}

### Requirements

${formatSignals(requirementSignals)}

### UI

${formatSignals(uiSignals)}

### API

${formatSignals(apiSignals)}

${formatFrontendDeliveryBlueprintSection(brief, requirementSignals, uiSignals, apiSignals)}

${brief?.openQuestions.length ? `## Open Questions\n\n${brief.openQuestions.map((question) => `- ${question}`).join("\n")}\n` : ""}

## Assumptions

- Existing component, routing, styling, and data-fetching conventions should be reused.
- Missing product behavior should be clarified before code-changing work begins.
- API failures need visible user-facing states.
- Generated code should be split into small, reviewable changes.

## Implementation Phases

### Phase 1: Repository Discovery

- Confirm framework, package manager, route structure, styling approach, and test setup.
- Identify existing reusable components and data-fetching helpers.
- Record commands for install, dev server, lint, typecheck, and tests.

### Phase 2: Product And UI Mapping

- Convert requirements into user stories and acceptance checks.
- Map UI notes into screens, components, states, and responsive rules.
- Identify empty, loading, error, disabled, and success states.
- Flag missing copy, validation rules, or navigation behavior.

### Phase 3: API Integration Design

- Map API endpoints to frontend data needs.
- Define request, response, error, and auth handling.
- Decide where data fetching and caching should live.
- Add mock data or fixtures if the API is unavailable during development.

### Phase 4: Implementation

- Build or update routes.
- Build components in the smallest reusable units that match the existing codebase.
- Connect state and API calls.
- Implement loading, empty, error, and optimistic or success states where required.
- Keep styling aligned with the existing design system.

### Phase 5: Verification

- Run formatting, linting, typechecking, and tests.
- Manually check the primary user flows.
- Check responsive layouts at mobile, tablet, and desktop widths.
- Verify keyboard navigation, labels, focus states, and semantic structure.
- Capture known gaps in the delivery report.

## Component And Route Breakdown

- Routes: derive from the UI screen list and existing router conventions.
- Page components: own data loading and high-level layout.
- Feature components: own interaction-heavy sections.
- Shared components: extract only when reused or already established by the codebase.
- API client modules: keep transport and schema assumptions isolated from UI.

## Verification Checklist

${formatAcceptanceCriteria(brief)}
- [ ] UI states cover loading, empty, error, and success.
- [ ] API integration handles auth, validation, and failure cases.
- [ ] Responsive behavior is checked.
- [ ] Accessibility basics are checked.
- [ ] Existing tests still pass.
- [ ] New behavior has focused tests or documented manual QA.
- [ ] Delivery report lists changed files, commands run, and known risks.

${brief?.recommendedVerification.length ? `## Recommended Commands\n\n${brief.recommendedVerification.map((command) => `- \`${command}\``).join("\n")}\n` : ""}

## Delivery Risks

${formatDeliveryRisks(brief)}
`;
}

function normalizeProviderPlan(plan: string, context: ProjectContext, brief?: ProjectBrief): string {
  const trimmed = plan.trim();

  if (!trimmed || looksLikePatchSetJson(trimmed)) {
    return createFallbackPlan(context, brief);
  }

  if (hasFrontendDeliveryBlueprint(trimmed)) {
    return `${trimmed}\n`;
  }

  const requirementSignals = brief?.signals.requirements ?? extractMarkdownSignals(context.requirements);
  const uiSignals = brief?.signals.ui ?? extractMarkdownSignals(context.ui);
  const apiSignals = brief?.signals.api ?? extractMarkdownSignals(context.api);

  return `${trimmed}\n\n${formatFrontendDeliveryBlueprintSection(brief, requirementSignals, uiSignals, apiSignals)}`;
}

function formatSignals(signals: string[]): string {
  if (signals.length === 0) {
    return "- No concrete signals found yet. Add more detail to improve the generated plan.";
  }

  return signals.map((signal) => `- ${signal}`).join("\n");
}

function formatStackSection(brief: ProjectBrief): string {
  const stack = brief.stack;
  const detected = [
    stack.packageManager ? `Package manager: ${stack.packageManager}` : undefined,
    stack.runtimes.length ? `Runtime: ${stack.runtimes.join(", ")}` : undefined,
    stack.frameworks.length ? `Frameworks: ${stack.frameworks.join(", ")}` : undefined,
    stack.buildTools.length ? `Build tools: ${stack.buildTools.join(", ")}` : undefined,
    stack.styling.length ? `Styling: ${stack.styling.join(", ")}` : undefined,
    stack.testing.length ? `Testing: ${stack.testing.join(", ")}` : undefined,
    stack.sourceDirectories.length ? `Source directories: ${stack.sourceDirectories.join(", ")}` : undefined
  ].filter((line): line is string => Boolean(line));

  if (detected.length === 0) {
    return "### Repository Stack\n\n- No repository stack signals detected yet.\n";
  }

  return `### Repository Stack\n\n${detected.map((line) => `- ${line}`).join("\n")}\n`;
}

function formatRequirementDetailsSection(brief: ProjectBrief): string {
  const sections = [
    formatRequirementList("User Stories", brief.userStories, "No explicit user stories were found in the requirements document."),
    formatRequirementList("Requirement Constraints", brief.constraints, "No explicit requirement constraints were found.")
  ];

  return sections.join("\n\n");
}

function formatRequirementList(title: string, items: string[], emptyMessage: string): string {
  const body = items.length ? items.map((item) => `- ${item}`).join("\n") : `- ${emptyMessage}`;

  return `## ${title}\n\n${body}\n`;
}

function formatDesignAssetsSection(brief: ProjectBrief): string {
  if (brief.designAssets.length === 0) {
    return "## Design Assets\n\n- No UI design assets were referenced from the UI notes.\n";
  }

  return `## Design Assets\n\n${brief.designAssets.map(formatDesignAsset).join("\n")}\n`;
}

function formatDesignAsset(asset: ProjectBrief["designAssets"][number]): string {
  const details = [
    asset.kind,
    asset.altText ? `alt: ${asset.altText}` : undefined,
    asset.resolvedPath ? `resolved: ${asset.resolvedPath}` : undefined,
    asset.exists === undefined ? undefined : `exists: ${asset.exists ? "yes" : "no"}`
  ].filter((value): value is string => Boolean(value));
  const metadata = formatDesignAssetMetadata(asset.metadata);

  return [
    `- \`${asset.reference}\` (${details.join(", ")})`,
    ...metadata.map((line) => `  - ${line}`)
  ].join("\n");
}

function formatDesignAssetMetadata(metadata: ProjectBrief["designAssets"][number]["metadata"]): string[] {
  if (!metadata) {
    return [];
  }

  return [
    metadata.width || metadata.height ? `Dimensions: ${metadata.width ?? "unknown"}x${metadata.height ?? "unknown"}` : undefined,
    metadata.viewBox ? `ViewBox: ${metadata.viewBox}` : undefined,
    metadata.title ? `Title: ${metadata.title}` : undefined,
    metadata.description ? `Description: ${metadata.description}` : undefined,
    metadata.colors?.length ? `Colors: ${metadata.colors.join(", ")}` : undefined,
    metadata.textSnippets?.length ? `Text snippets: ${metadata.textSnippets.join("; ")}` : undefined
  ].filter((value): value is string => Boolean(value));
}

function formatUiStateChecklistSection(brief: ProjectBrief): string {
  const items = brief.uiStateChecklist ?? [];

  if (items.length === 0) {
    return "## UI State Checklist\n\n- No UI state checklist items were extracted from the UI notes.\n";
  }

  return `## UI State Checklist\n\n${items.map((item) => `- [${item.kind}] Line ${item.sourceLine}: ${item.summary}`).join("\n")}\n`;
}

function formatFrontendDeliveryBlueprintSection(
  brief: ProjectBrief | undefined,
  requirementSignals: string[],
  uiSignals: string[],
  apiSignals: string[]
): string {
  return `## Frontend Delivery Blueprint

### Routes And Navigation

${formatRoutesAndNavigation(brief, requirementSignals, uiSignals)}

### Components

${formatComponentsBlueprint(brief, uiSignals)}

### State And Interaction

${formatStateAndInteractionBlueprint(brief, uiSignals)}

### Data And API Integration

${formatDataIntegrationBlueprint(brief, apiSignals)}

### Styling And Responsive Rules

${formatStylingBlueprint(brief, uiSignals)}

### Test Plan

${formatTestBlueprint(brief)}

### Accessibility Checks

${formatAccessibilityBlueprint(brief)}
`;
}

function formatRoutesAndNavigation(
  brief: ProjectBrief | undefined,
  requirementSignals: string[],
  uiSignals: string[]
): string {
  const routeTargets = formatFrontendTargetItems(brief?.frontendTargets?.routes);
  const screenItems = uiChecklistItems(brief, "screen").map(
    (item) => `Define a route or view boundary for UI screen note at line ${item.sourceLine}: ${item.summary}`
  );
  const storyItems = (brief?.userStories ?? requirementSignals).slice(0, 4).map(
    (story) => `Ensure navigation exposes the user path for: ${story}`
  );
  const fallbackItems = uiSignals.slice(0, 4).map((signal) => `Derive route or view ownership from UI signal: ${signal}`);

  return formatPlanBullets(
    unique([...routeTargets, ...screenItems, ...storyItems, ...fallbackItems]).slice(0, 8),
    "Identify route, page, or view boundaries from the UI notes and existing router conventions."
  );
}

function formatComponentsBlueprint(brief: ProjectBrief | undefined, uiSignals: string[]): string {
  const componentTargets = formatFrontendTargetItems(brief?.frontendTargets?.components);
  const componentItems = uiChecklistItems(brief, "component").map(
    (item) => `Create or update component boundary from UI note line ${item.sourceLine}: ${item.summary}`
  );
  const assetItems = (brief?.designAssets ?? []).slice(0, 4).map((asset) =>
    `Use design asset ${asset.altText ? `"${asset.altText}"` : `\`${asset.reference}\``} as visual evidence for layout and component composition.`
  );
  const fallbackItems = componentItems.length || assetItems.length
    ? []
    : uiSignals.slice(0, 4).map((signal) => `Map UI signal to page, feature, or shared component ownership: ${signal}`);

  return formatPlanBullets(
    unique([
      "Keep page-level components responsible for layout and data orchestration.",
      "Keep reusable feature components focused on one interaction or display responsibility.",
      ...componentTargets,
      ...componentItems,
      ...assetItems,
      ...fallbackItems
    ]).slice(0, 10),
    "Define page, feature, and shared component boundaries before coding."
  );
}

function formatStateAndInteractionBlueprint(brief: ProjectBrief | undefined, uiSignals: string[]): string {
  const stateTargets = formatFrontendTargetItems(brief?.frontendTargets?.uiStates);
  const stateItems = uiChecklistItems(brief, "state").map(
    (item) => `Implement documented UI state from line ${item.sourceLine}: ${item.summary}`
  );
  const interactionItems = uiChecklistItems(brief, "interaction").map(
    (item) => `Implement documented interaction from line ${item.sourceLine}: ${item.summary}`
  );
  const errorItems = (brief?.apiErrorCases ?? []).map(
    (item) => `Map API failure at line ${item.sourceLine} to visible retry, stale, unavailable, or blocked UI behavior: ${item.summary}`
  );
  const fallbackItems = stateItems.length || interactionItems.length || errorItems.length
    ? []
    : uiSignals.slice(0, 4).map((signal) => `Identify loading, empty, error, success, and interaction states for: ${signal}`);

  return formatPlanBullets(
    unique([...stateTargets, ...stateItems, ...interactionItems, ...errorItems, ...fallbackItems]).slice(0, 10),
    "Cover loading, empty, error, success, disabled, and user-triggered interaction states."
  );
}

function formatDataIntegrationBlueprint(brief: ProjectBrief | undefined, apiSignals: string[]): string {
  const dataTargets = formatFrontendTargetItems(brief?.frontendTargets?.dataNeeds);
  const contractItems = (brief?.apiContracts ?? []).map(
    (contract) => `Integrate \`${contract.method} ${contract.path}\` from API line ${contract.sourceLine}: ${contract.summary}`
  );
  const modelItems = (brief?.apiDataModels ?? []).map((model) => {
    const fields = model.fields.length ? model.fields.join(", ") : "no fields listed";

    return `Shape UI data around \`${model.name}\` fields: ${fields}.`;
  });
  const authItems = (brief?.apiAuthRequirements ?? []).map(
    (item) => `Account for API auth requirement at line ${item.sourceLine}: ${item.summary}`
  );
  const fallbackItems = contractItems.length || modelItems.length || authItems.length
    ? []
    : apiSignals.slice(0, 5).map((signal) => `Translate API signal into data-fetching and error-handling work: ${signal}`);

  return formatPlanBullets(
    unique([
      ...dataTargets,
      ...contractItems,
      ...modelItems,
      ...authItems,
      ...fallbackItems,
      "Keep transport, mapping, and mock or fixture data isolated from presentation components."
    ]).slice(0, 12),
    "Map API contracts into data clients, data shapes, auth handling, and UI state transitions."
  );
}

function formatStylingBlueprint(brief: ProjectBrief | undefined, uiSignals: string[]): string {
  const responsiveItems = uiChecklistItems(brief, "responsive").map(
    (item) => `Apply responsive rule from UI note line ${item.sourceLine}: ${item.summary}`
  );
  const stylingItems = brief?.stack.styling.length
    ? [`Use detected styling approach: ${brief.stack.styling.join(", ")}.`]
    : [];
  const assetItems = (brief?.designAssets ?? []).flatMap((asset) => {
    const colors = asset.metadata?.colors?.length ? `Color references: ${asset.metadata.colors.join(", ")}.` : undefined;
    const dimensions = asset.metadata?.width || asset.metadata?.height
      ? `Design dimensions: ${asset.metadata.width ?? "unknown"}x${asset.metadata.height ?? "unknown"}.`
      : undefined;

    return [colors, dimensions].filter((item): item is string => Boolean(item));
  }).slice(0, 4);
  const fallbackItems = responsiveItems.length || stylingItems.length || assetItems.length
    ? []
    : uiSignals.slice(0, 3).map((signal) => `Derive spacing, density, and responsive treatment from UI signal: ${signal}`);

  return formatPlanBullets(
    unique([
      ...stylingItems,
      ...responsiveItems,
      ...assetItems,
      ...fallbackItems,
      "Check text fit and layout stability across desktop, tablet, and mobile widths."
    ]).slice(0, 10),
    "Follow existing styling conventions and verify responsive layout behavior."
  );
}

function formatTestBlueprint(brief: ProjectBrief | undefined): string {
  const acceptanceItems = (brief?.acceptanceCriteria ?? []).slice(0, 6).map(
    (criterion) => `Cover acceptance criterion with automated test or documented manual QA: ${criterion}`
  );
  const commandItems = (brief?.recommendedVerification ?? []).map((command) => `Run verification command: \`${command}\``);
  const testingItems = brief?.stack.testing.length ? [`Use detected test stack: ${brief.stack.testing.join(", ")}.`] : [];

  return formatPlanBullets(
    unique([
      ...testingItems,
      ...acceptanceItems,
      ...commandItems,
      "Add focused tests for data mapping, visible states, and critical user interactions when the repository has a matching test setup."
    ]).slice(0, 12),
    "Define automated or manual checks for each acceptance criterion and run the detected verification commands."
  );
}

function formatAccessibilityBlueprint(brief: ProjectBrief | undefined): string {
  const accessibilityItems = uiChecklistItems(brief, "accessibility").map(
    (item) => `Honor accessibility note from UI line ${item.sourceLine}: ${item.summary}`
  );

  return formatPlanBullets(
    unique([
      ...accessibilityItems,
      "Use semantic landmarks, headings, labels, and button/link roles that match the interaction.",
      "Verify keyboard navigation, focus visibility, and screen-reader friendly state changes.",
      "Confirm color and text treatments remain readable in documented visual states."
    ]).slice(0, 8),
    "Check semantic structure, keyboard access, focus states, labels, and state announcements."
  );
}

function uiChecklistItems(
  brief: ProjectBrief | undefined,
  kind: ProjectBrief["uiStateChecklist"][number]["kind"]
): ProjectBrief["uiStateChecklist"] {
  return (brief?.uiStateChecklist ?? []).filter((item) => item.kind === kind);
}

function formatFrontendTargetItems(
  items: NonNullable<ProjectBrief["frontendTargets"]>[keyof NonNullable<ProjectBrief["frontendTargets"]>] | undefined
): string[] {
  return (items ?? []).map((item) => {
    const location = item.sourceLine === undefined ? item.source : `${item.source} line ${item.sourceLine}`;
    const evidence = item.evidence.length ? ` Evidence: ${item.evidence.join("; ")}.` : "";

    return `${item.summary} (${location}).${evidence}`;
  });
}

function formatPlanBullets(items: string[], emptyMessage: string): string {
  return items.length ? items.map((item) => `- ${item}`).join("\n") : `- ${emptyMessage}`;
}

function hasFrontendDeliveryBlueprint(plan: string): boolean {
  return [
    "## Frontend Delivery Blueprint",
    "### Routes And Navigation",
    "### Components",
    "### State And Interaction",
    "### Data And API Integration",
    "### Styling And Responsive Rules",
    "### Test Plan",
    "### Accessibility Checks"
  ].every((heading) => plan.includes(heading));
}

function looksLikePatchSetJson(text: string): boolean {
  const fencedJson = /```(?:json)?\s*([\s\S]*?)```/.exec(text);
  const candidate = fencedJson?.[1] ?? text;

  try {
    const parsed = JSON.parse(candidate) as {
      version?: unknown;
      taskId?: unknown;
      operations?: unknown;
    };

    return parsed.version === 1 && typeof parsed.taskId === "string" && Array.isArray(parsed.operations);
  } catch {
    return false;
  }
}

function formatDeliveryRisks(brief: ProjectBrief | undefined): string {
  const risks = brief?.deliveryRisks ?? [];

  if (risks.length === 0) {
    return [
      "- Requirements may be too ambiguous for autonomous coding.",
      "- UI notes may omit responsive or interactive states.",
      "- API docs may not include error shape or auth behavior.",
      "- Existing repository conventions may override generic implementation choices."
    ].join("\n");
  }

  return risks.map((risk) => {
    const source = risk.sourceLine === undefined ? risk.source : `${risk.source}:${risk.sourceLine}`;

    return `- [${risk.level}] ${source}: ${risk.summary} Recommendation: ${risk.recommendation}`;
  }).join("\n");
}

function formatApiContractsSection(brief: ProjectBrief): string {
  if (brief.apiContracts.length === 0) {
    return "## API Contracts\n\n- No recognizable HTTP endpoint contracts were found in the API docs.\n";
  }

  return `## API Contracts\n\n${brief.apiContracts.map(formatApiContract).join("\n")}\n`;
}

function formatApiContract(contract: ProjectBrief["apiContracts"][number]): string {
  return `- \`${contract.method} ${contract.path}\` (line ${contract.sourceLine}): ${contract.summary}`;
}

function formatApiDataModelsSection(brief: ProjectBrief): string {
  if (brief.apiDataModels.length === 0 && brief.invalidApiDataModels.length === 0) {
    return "## API Data Models\n\n- No JSON or OpenAPI data model blocks were found in the API docs.\n";
  }

  const models = brief.apiDataModels.map((model) => {
    const fields = model.fields.length ? model.fields.join(", ") : "no fields listed";

    return `- \`${model.name}\` (line ${model.sourceLine}): ${fields}`;
  });
  const invalid = brief.invalidApiDataModels.map(
    (model) => `- Invalid API data model at line ${model.sourceLine}: ${model.error}`
  );

  return `## API Data Models\n\n${[...models, ...invalid].join("\n")}\n`;
}

function formatApiOperationalConstraintsSection(brief: ProjectBrief): string {
  const errorCases = brief.apiErrorCases.length
    ? brief.apiErrorCases.map((item) => `- Line ${item.sourceLine}: ${item.summary}`).join("\n")
    : "- No explicit API error cases were found.";
  const authRequirements = brief.apiAuthRequirements.length
    ? brief.apiAuthRequirements.map((item) => `- Line ${item.sourceLine}: ${item.summary}`).join("\n")
    : "- No explicit API authentication or authorization requirements were found.";

  return `## API Error Cases\n\n${errorCases}\n\n## API Auth Requirements\n\n${authRequirements}\n`;
}

function formatAcceptanceCriteria(brief: ProjectBrief | undefined): string {
  if (!brief?.acceptanceCriteria.length) {
    return "- [ ] Requirements are represented as acceptance criteria.";
  }

  return brief.acceptanceCriteria.map((item) => `- [ ] ${item}`).join("\n");
}

function unique(values: string[]): string[] {
  return [...new Set(values.filter((value) => value.trim().length > 0))];
}
