import type { ProjectBrief } from "./brief.js";
import type { ExecutionLog } from "./execution-log.js";
import type { AppliedPatchOperation, AppliedPatchReport } from "./patch-set.js";
import type { VerificationReport } from "./verification.js";
import type { VisualReport } from "./visual.js";

export interface DeliveryReportInput {
  brief: ProjectBrief | undefined;
  implementationPlanPath: string;
  projectBriefPath: string;
  taskPlanPath: string;
  taskPlanMarkdownPath: string;
  patchProposalsDir: string;
  executionLogPath: string;
  executionLog: ExecutionLog | undefined;
  rollbackReportPath: string;
  verificationReportPath: string;
  verification: VerificationReport | undefined;
  visualReportPath: string;
  visualReport: VisualReport | undefined;
}

export function formatDeliveryReport(input: DeliveryReportInput): string {
  const verification = input.verification;
  const brief = input.brief;

  return `# Delivery Report

Generated by DevFlow.

## Artifacts

- Project brief: \`${input.projectBriefPath}\`
- Implementation plan: \`${input.implementationPlanPath}\`
- Task plan: \`${input.taskPlanPath}\`
- Task plan markdown: \`${input.taskPlanMarkdownPath}\`
- Patch proposals: \`${input.patchProposalsDir}\`
- Execution log: \`${input.executionLogPath}\`
- Rollback report: \`${input.rollbackReportPath}\`
- Verification report: \`${input.verificationReportPath}\`
- Visual report: \`${input.visualReportPath}\`

## Source Documents

${brief ? `- Requirements: \`${brief.sourceDocuments.requirementsPath}\`
- UI notes: \`${brief.sourceDocuments.uiPath}\`
- API docs: \`${brief.sourceDocuments.apiPath}\`` : "- Project brief was not available."}

## User Stories

${brief ? formatRequirementList(brief.userStories, "No explicit user stories were found in the requirements document.") : "- Project brief was not available."}

## Requirement Constraints

${brief ? formatRequirementList(brief.constraints, "No explicit requirement constraints were found.") : "- Project brief was not available."}

## Acceptance Criteria

${brief ? formatAcceptanceCriteria(brief) : "- Project brief was not available."}

## Design Assets

${brief ? formatDesignAssets(brief) : "- Project brief was not available."}

## API Contracts

${brief ? formatApiContracts(brief) : "- Project brief was not available."}

## API Data Models

${brief ? formatApiDataModels(brief) : "- Project brief was not available."}

## API Error Cases

${brief ? formatApiErrorCases(brief) : "- Project brief was not available."}

## API Auth Requirements

${brief ? formatApiAuthRequirements(brief) : "- Project brief was not available."}

## Repository Stack

${brief ? formatStack(brief) : "- Stack profile was not available."}

## Applied Changes

${input.executionLog ? formatExecutionLog(input.executionLog) : "- Execution log was not available."}

## Verification

${verification ? formatVerification(verification) : "- Verification has not been run yet."}

## Visual Verification

${input.visualReport ? formatVisual(input.visualReport) : "- Visual verification has not been run yet."}

## Delivery Readiness

${formatDeliveryReadiness(input)}

## Open Questions

${brief?.openQuestions.length ? brief.openQuestions.map((question) => `- ${question}`).join("\n") : "- No open questions recorded."}

## Next Actions

- Review the implementation plan against the source documents.
- Review acceptance criteria against verification and visual evidence.
- Review dry-run patch proposals before source-changing execution.
- Resolve open questions before autonomous code-changing work.
- Run or re-run verification after implementation changes.
${input.visualReport ? "- Review visual screenshots before handoff." : "- Attach screenshots or preview URLs once UI execution exists."}
`;
}

function formatAcceptanceCriteria(brief: ProjectBrief): string {
  if (brief.acceptanceCriteria.length === 0) {
    return "- No explicit acceptance criteria were found in the requirements document.";
  }

  return brief.acceptanceCriteria.map((criterion) => `- ${criterion}`).join("\n");
}

function formatRequirementList(items: string[], emptyMessage: string): string {
  return items.length ? items.map((item) => `- ${item}`).join("\n") : `- ${emptyMessage}`;
}

function formatDeliveryReadiness(input: DeliveryReportInput): string {
  const blockers: string[] = [];
  const evidence: string[] = [];

  if (!input.brief) {
    blockers.push("Project brief was not available.");
  } else {
    if (input.brief.acceptanceCriteria.length === 0) {
      blockers.push("Requirements do not include explicit acceptance criteria.");
    } else {
      evidence.push(`${input.brief.acceptanceCriteria.length} acceptance criteria recorded.`);
    }

    if (input.brief.openQuestions.length > 0) {
      blockers.push(`${input.brief.openQuestions.length} open question(s) remain.`);
    }
  }

  if (!input.verification) {
    blockers.push("Verification has not been run.");
  } else if (input.verification.status !== "passed") {
    blockers.push(`Verification status is ${input.verification.status}.`);
  } else {
    evidence.push("Verification passed.");
  }

  if (!input.visualReport) {
    evidence.push("Visual verification was not run for this delivery.");
  } else if (input.visualReport.status !== "passed") {
    blockers.push(`Visual verification status is ${input.visualReport.status}.`);
  } else {
    evidence.push("Visual verification passed.");
  }

  const status = blockers.length ? "needs attention" : "ready for review";
  const lines = [`- Status: ${status}`, ...evidence.map((item) => `- Evidence: ${item}`)];

  if (blockers.length) {
    lines.push(...blockers.map((item) => `- Attention: ${item}`));
  }

  return lines.join("\n");
}

function formatStack(brief: ProjectBrief): string {
  const stack = brief.stack;
  const lines = [
    stack.packageManager ? `Package manager: ${stack.packageManager}` : undefined,
    stack.runtimes.length ? `Runtime: ${stack.runtimes.join(", ")}` : undefined,
    stack.frameworks.length ? `Frameworks: ${stack.frameworks.join(", ")}` : undefined,
    stack.buildTools.length ? `Build tools: ${stack.buildTools.join(", ")}` : undefined,
    stack.styling.length ? `Styling: ${stack.styling.join(", ")}` : undefined,
    stack.testing.length ? `Testing: ${stack.testing.join(", ")}` : undefined,
    stack.sourceDirectories.length ? `Source directories: ${stack.sourceDirectories.join(", ")}` : undefined
  ].filter((line): line is string => Boolean(line));

  return lines.length ? lines.map((line) => `- ${line}`).join("\n") : "- No stack signals recorded.";
}

function formatDesignAssets(brief: ProjectBrief): string {
  if (brief.designAssets.length === 0) {
    return "- No UI design assets were referenced from the UI notes.";
  }

  return brief.designAssets.map((asset) => {
    const details = [
      asset.kind,
      asset.altText ? `alt: ${asset.altText}` : undefined,
      asset.resolvedPath ? `resolved: ${asset.resolvedPath}` : undefined,
      asset.exists === undefined ? undefined : `exists: ${asset.exists ? "yes" : "no"}`
    ].filter((value): value is string => Boolean(value));
    const metadata = formatDesignAssetMetadata(asset.metadata);

    return [
      `- \`${asset.reference}\`: ${details.join(", ")}`,
      ...metadata.map((line) => `  - ${line}`)
    ].join("\n");
  }).join("\n");
}

function formatDesignAssetMetadata(metadata: ProjectBrief["designAssets"][number]["metadata"]): string[] {
  if (!metadata) {
    return [];
  }

  return [
    metadata.width || metadata.height ? `Dimensions: ${metadata.width ?? "unknown"}x${metadata.height ?? "unknown"}` : undefined,
    metadata.viewBox ? `ViewBox: ${metadata.viewBox}` : undefined,
    metadata.title ? `Title: ${metadata.title}` : undefined,
    metadata.description ? `Description: ${metadata.description}` : undefined,
    metadata.colors?.length ? `Colors: ${metadata.colors.join(", ")}` : undefined,
    metadata.textSnippets?.length ? `Text snippets: ${metadata.textSnippets.join("; ")}` : undefined
  ].filter((line): line is string => Boolean(line));
}

function formatApiContracts(brief: ProjectBrief): string {
  if (brief.apiContracts.length === 0) {
    return "- No recognizable HTTP endpoint contracts were found in the API docs.";
  }

  return brief.apiContracts
    .map((contract) => `- \`${contract.method} ${contract.path}\` (line ${contract.sourceLine}): ${contract.summary}`)
    .join("\n");
}

function formatApiDataModels(brief: ProjectBrief): string {
  if (brief.apiDataModels.length === 0 && brief.invalidApiDataModels.length === 0) {
    return "- No JSON or OpenAPI data model blocks were found in the API docs.";
  }

  const models = brief.apiDataModels.map((model) => {
    const fields = model.fields.length ? model.fields.join(", ") : "no fields listed";

    return `- \`${model.name}\` (line ${model.sourceLine}): ${fields}`;
  });
  const invalid = brief.invalidApiDataModels.map(
    (model) => `- Invalid API data model at line ${model.sourceLine}: ${model.error}`
  );

  return [...models, ...invalid].join("\n");
}

function formatApiErrorCases(brief: ProjectBrief): string {
  if (brief.apiErrorCases.length === 0) {
    return "- No explicit API error cases were found.";
  }

  return brief.apiErrorCases.map((item) => `- Line ${item.sourceLine}: ${item.summary}`).join("\n");
}

function formatApiAuthRequirements(brief: ProjectBrief): string {
  if (brief.apiAuthRequirements.length === 0) {
    return "- No explicit API authentication or authorization requirements were found.";
  }

  return brief.apiAuthRequirements.map((item) => `- Line ${item.sourceLine}: ${item.summary}`).join("\n");
}

function formatVerification(report: VerificationReport): string {
  if (report.status === "skipped") {
    return "- Verification was skipped because no commands were available.";
  }

  const summary = [`- Status: ${report.status}`, `- Started: ${report.startedAt}`, `- Finished: ${report.finishedAt}`];
  const commands = report.results.map(
    (result) => `- \`${result.command}\`: exit ${result.exitCode ?? "unknown"} in ${result.durationMs}ms`
  );

  return [...summary, ...commands].join("\n");
}

function formatExecutionLog(log: ExecutionLog): string {
  if (log.entries.length === 0) {
    return "- No source-changing patch sets have been applied.";
  }

  const recentEntries = log.entries.slice(-5);
  const omitted = log.entries.length - recentEntries.length;
  const summary = formatExecutionSummary(log);

  if (omitted > 0) {
    summary.push(`- Showing latest ${recentEntries.length}; ${omitted} older entries omitted.`);
  }

  return [...summary, ...recentEntries.map(formatExecutionEntry)].join("\n");
}

function formatExecutionEntry(entry: AppliedPatchReport): string {
  const lines = [
    `- ${entry.taskId}: ${entry.status} at ${entry.appliedAt}`,
    `  - Summary: ${entry.summary}`,
    entry.backupManifestPath ? `  - Backup: \`${entry.backupManifestPath}\`` : undefined,
    ...entry.operations.map(formatPatchOperation)
  ].filter((line): line is string => Boolean(line));

  return lines.join("\n");
}

function formatPatchOperation(operation: AppliedPatchOperation): string {
  const details = [
    operation.status,
    `${operation.bytesWritten} bytes`,
    operation.replacements === undefined ? undefined : `${operation.replacements} replacements`,
    formatLineStats(operation)
  ].filter((value): value is string => Boolean(value));

  return `  - ${operation.type} \`${operation.path}\`: ${details.join(", ")}`;
}

function formatExecutionSummary(log: ExecutionLog): string[] {
  const operations = log.entries.flatMap((entry) => entry.operations);
  const touchedFiles = unique(operations.map((operation) => operation.path));
  const writtenOperations = operations.filter((operation) => operation.status === "written").length;
  const deletedOperations = operations.filter((operation) => operation.status === "deleted").length;
  const unchangedOperations = operations.filter((operation) => operation.status === "unchanged").length;
  const backups = log.entries.filter((entry) => Boolean(entry.backupManifestPath)).length;

  return [
    `- Entries recorded: ${log.entries.length}`,
    touchedFiles.length ? `- Files touched: ${formatTouchedFiles(touchedFiles)}` : undefined,
    `- Written operations: ${writtenOperations}`,
    deletedOperations ? `- Deleted operations: ${deletedOperations}` : undefined,
    `- Unchanged operations: ${unchangedOperations}`,
    backups ? `- Backups recorded: ${backups}` : undefined
  ].filter((line): line is string => Boolean(line));
}

function formatTouchedFiles(paths: string[]): string {
  const shown = paths.slice(0, 8).map((path) => `\`${path}\``).join(", ");
  const omitted = paths.length - 8;

  return omitted > 0 ? `${shown}, and ${omitted} more` : shown;
}

function formatLineStats(operation: AppliedPatchOperation): string | undefined {
  if (operation.linesBefore === undefined || operation.linesAfter === undefined || operation.lineDelta === undefined) {
    return undefined;
  }

  return `lines ${operation.linesBefore}->${operation.linesAfter} (${formatSignedNumber(operation.lineDelta)})`;
}

function formatSignedNumber(value: number): string {
  return value > 0 ? `+${value}` : String(value);
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

function formatVisual(report: VisualReport): string {
  const summary = [`- Status: ${report.status}`, `- URL: ${report.url}`];
  const screenshots = report.screenshots.map(
    (screenshot) => {
      const analysis = screenshot.analysis
        ? `, blank: ${screenshot.analysis.blank ? "yes" : "no"}, distinct pixels: ${formatRatio(screenshot.analysis.distinctPixelRatio)}`
        : "";

      return `- ${screenshot.viewport.name} ${screenshot.viewport.width}x${screenshot.viewport.height}: \`${screenshot.path}\`${analysis}`;
    }
  );
  const textChecks = report.requiredText.map((check) => `- Text "${check.text}": ${check.found ? "found" : "missing"}`);
  const layoutIssues = report.layoutIssues?.length
    ? report.layoutIssues.map(
      (issue) =>
        `- Layout ${issue.viewport.name} ${issue.type} at ${issue.selector}: ${issue.message}${issue.text ? ` Text: "${issue.text}"` : ""}`
    )
    : ["- Layout issues: none"];

  return [...summary, ...screenshots, ...textChecks, ...layoutIssues].join("\n");
}

function formatRatio(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}
