import assert from "node:assert/strict";
import { test } from "node:test";
import { createDeliveryManifest, formatDeliveryReport, parseTaskChangelogSummary } from "./report.js";
import type { ProjectBrief } from "./brief.js";
import type { VerificationReport } from "./verification.js";

const brief: ProjectBrief = {
  version: 1,
  sourceDocuments: {
    requirementsPath: "docs/requirements.md",
    uiPath: "docs/ui.md",
    apiPath: "docs/api.md"
  },
  stack: {
    packageManager: "npm",
    runtimes: ["Node.js", "TypeScript"],
    frameworks: ["React"],
    buildTools: ["Vite"],
    styling: [],
    testing: ["Vitest"],
    scripts: {
      check: "vitest run"
    },
    workspacePackages: [
      {
        name: "@acme/web",
        path: "apps/web",
        scripts: {
          check: "vitest run"
        }
      }
    ],
    sourceDirectories: ["apps/web/src"],
    configFiles: ["vite.config.ts"],
    notes: []
  },
  signals: {
    requirements: [],
    ui: [],
    api: []
  },
  designAssets: [
    {
      source: "ui-markdown-image",
      kind: "local",
      altText: "Dashboard mock",
      reference: "assets/dashboard.svg",
      resolvedPath: "docs/assets/dashboard.svg",
      exists: true,
      metadata: {
        width: "960",
        height: "640",
        viewBox: "0 0 960 640",
        title: "Dashboard mock",
        description: "Operational dashboard wireframe.",
        colors: ["#f8fafc", "#0f172a", "rgb(34, 197, 94)"],
        textSnippets: ["Release health", "Deploy confidence"]
      }
    }
  ],
  designTokens: [
    {
      category: "color",
      sourceLine: 18,
      name: "Primary color",
      value: "#2563eb",
      summary: "Primary color: #2563eb"
    }
  ],
  uiStateChecklist: [
    {
      kind: "state",
      sourceLine: 10,
      summary: "Loading state uses skeleton table rows."
    },
    {
      kind: "responsive",
      sourceLine: 14,
      summary: "Tablet layout keeps the KPI strip above the table."
    }
  ],
  apiContracts: [
    {
      method: "GET",
      path: "/api/dashboard",
      sourceLine: 12,
      summary: "GET /api/dashboard",
      parameters: [
        {
          name: "range",
          in: "query",
          required: false,
          defaultValue: "7d",
          summary: "query parameter range default 7d"
        }
      ]
    }
  ],
  apiDataModels: [
    {
      name: "dashboard",
      sourceLine: 20,
      fields: ["releaseHealth", "deployConfidence"],
      summary: "dashboard object"
    }
  ],
  apiErrorCases: [
    {
      sourceLine: 30,
      summary: "Dashboard endpoint unavailable: show stale values."
    }
  ],
  apiAuthRequirements: [
    {
      sourceLine: 34,
      summary: "Authorization: Bearer token is required."
    }
  ],
  apiStateRequirements: [
    {
      sourceLine: 38,
      summary: "Keep last known dashboard values during background refresh."
    }
  ],
  invalidApiDataModels: [],
  userStories: ["As a release owner, I want dashboard health visible so that release risk is clear."],
  constraints: ["Keep the dashboard dense and operational."],
  acceptanceCriteria: ["Dashboard renders release health.", "Keep last known dashboard values during background refresh."],
  deliveryRisks: [
    {
      level: "high",
      source: "requirements",
      sourceLine: 8,
      summary: "Requirement contains an unresolved placeholder: TODO confirm empty state copy.",
      recommendation: "Resolve the placeholder before source-changing execution."
    },
    {
      level: "medium",
      source: "ui",
      summary: "UI checklist does not include responsive behavior.",
      recommendation: "Document desktop, tablet, and mobile expectations before visual verification."
    }
  ],
  openQuestions: ["Confirm empty state copy."],
  recommendedVerification: ["npm run check"]
};

const verification: VerificationReport = {
  startedAt: "2026-01-01T00:00:00.000Z",
  finishedAt: "2026-01-01T00:00:01.000Z",
  status: "passed",
  results: [
    {
      command: "npm run check",
      exitCode: 0,
      durationMs: 1000,
      stdout: "ok",
      stderr: ""
    }
  ]
};

const taskChangelogMarkdown = `# Task Changelog

Generated by DevFlow from \`.devflow/artifacts/execution-log.json\`.

## Summary

- Entries: 1

## Review Handoff

- Execution log: \`.devflow/artifacts/execution-log.json\`
- Verification report: \`.devflow/artifacts/verification-report.json\`
- Delivery report: \`.devflow/artifacts/delivery-report.md\`
- Reviewer notes:
  - Review the operation list before merging or continuing source-changing work.
  - Reviewer should check generated copy before merge.

## Entries

- T03-code-implementation

<!-- devflow-verification-summary:start -->
## Verification Summary

- Status: passed
- Report: \`.devflow/artifacts/verification-report.json\`
- Finished at: 2026-01-01T00:00:01.000Z
- Commands passed: 1/1
- Commands:
  - \`npm run check\`: exit 0, 1000ms
<!-- devflow-verification-summary:end -->
`;

const taskChangelog = parseTaskChangelogSummary(taskChangelogMarkdown);

test("parseTaskChangelogSummary extracts review handoff and verification summary", () => {
  assert.equal(taskChangelog.reviewHandoff.executionLogPath, ".devflow/artifacts/execution-log.json");
  assert.equal(taskChangelog.reviewHandoff.verificationReportPath, ".devflow/artifacts/verification-report.json");
  assert.equal(taskChangelog.reviewHandoff.deliveryReportPath, ".devflow/artifacts/delivery-report.md");
  assert.deepEqual(taskChangelog.reviewHandoff.reviewerNotes, [
    "Review the operation list before merging or continuing source-changing work.",
    "Reviewer should check generated copy before merge."
  ]);
  assert.equal(taskChangelog.verificationSummary?.status, "passed");
  assert.equal(taskChangelog.verificationSummary?.reportPath, ".devflow/artifacts/verification-report.json");
  assert.equal(taskChangelog.verificationSummary?.finishedAt, "2026-01-01T00:00:01.000Z");
  assert.equal(taskChangelog.verificationSummary?.commandsPassed, "1/1");
  assert.deepEqual(taskChangelog.verificationSummary?.commands, ["npm run check: exit 0, 1000ms"]);
});

test("formatDeliveryReport includes artifacts, stack, verification, and questions", () => {
  const report = formatDeliveryReport({
    brief,
    implementationPlanPath: ".devflow/artifacts/implementation-plan.md",
    projectBriefPath: ".devflow/artifacts/project-brief.json",
    taskPlanPath: ".devflow/artifacts/tasks.json",
    taskPlanMarkdownPath: ".devflow/artifacts/tasks.md",
    patchProposalsDir: ".devflow/artifacts/patch-proposals",
    promptArtifactsDir: ".devflow/artifacts/prompts",
    sourceContextSummaryPath: ".devflow/artifacts/source-context-summary.json",
    sourceContextSummary: {
      version: 1,
      entries: [
        {
          generatedAt: "2026-01-01T00:00:00.250Z",
          mode: "dry-run",
          taskId: "T03-code-implementation",
          unit: {
            id: "U07",
            kind: "frontend-route",
            title: "Route path /dashboard"
          },
          entries: [
            { kind: "file", path: "src/App.tsx", sizeBytes: 2048, truncated: false },
            { kind: "missing", path: "src/pages/Dashboard.tsx" }
          ],
          omitted: ["src/legacy.tsx (entry limit reached)"],
          limits: {
            maxEntries: 14,
            maxFileBytes: 12_000,
            maxTotalBytes: 48_000,
            maxDirectoryEntries: 30
          }
        }
      ]
    },
    executionLogPath: ".devflow/artifacts/execution-log.json",
    taskChangelogPath: ".devflow/artifacts/task-changelog.md",
    taskChangelog,
    executionLog: {
      version: 1,
      entries: [
        {
          taskId: "T03-code-implementation",
          summary: "Apply dashboard source changes.",
          appliedAt: "2026-01-01T00:00:00.500Z",
          status: "applied",
          backupManifestPath: ".devflow/artifacts/backups/backup/manifest.json",
          operations: [
            {
              type: "replace",
              path: "src/App.tsx",
              status: "written",
              bytesWritten: 2048,
              replacements: 1,
              linesBefore: 80,
              linesAfter: 86,
              lineDelta: 6
            },
            {
              type: "delete",
              path: "src/ObsoletePanel.tsx",
              status: "deleted",
              bytesWritten: 0,
              linesBefore: 24,
              linesAfter: 0,
              lineDelta: -24
            }
          ]
        }
      ]
    },
    rollbackReportPath: ".devflow/artifacts/rollback-report.json",
    verificationReportPath: ".devflow/artifacts/verification-report.json",
    verification,
    visualReportPath: ".devflow/artifacts/visual/visual-report.json",
    visualReport: {
      startedAt: "2026-01-01T00:00:00.000Z",
      finishedAt: "2026-01-01T00:00:01.000Z",
      url: "http://127.0.0.1:5173",
      status: "failed",
      screenshots: [
        {
          viewport: { name: "desktop", width: 1440, height: 1000 },
          path: ".devflow/artifacts/visual/desktop.png",
          title: "OpsBoard",
          bodyCharacters: 100,
          analysis: {
            width: 1440,
            height: 1000,
            sampledPixels: 720000,
            distinctPixels: 180000,
            distinctPixelRatio: 0.25,
            blank: false
          }
        }
      ],
      layoutIssues: [
        {
          viewport: { name: "desktop", width: 1440, height: 1000 },
          type: "overlap",
          selector: "button.primary <-> span.badge",
          message: "Elements overlap by 120px^2 (30% of the smaller element).",
          text: "Deploy / Blocked"
        }
      ],
      requiredText: [{ text: "OpsBoard", found: true }]
    }
  });

  assert.match(report, /Delivery Report/);
  assert.match(report, /Task plan/);
  assert.match(report, /Prompt artifacts: `\.devflow\/artifacts\/prompts`/);
  assert.match(report, /Applied Changes/);
  assert.match(report, /Review Handoff/);
  assert.match(report, /Task changelog: `\.devflow\/artifacts\/task-changelog\.md`/);
  assert.match(report, /Reviewer should check generated copy before merge/);
  assert.match(report, /Latest changelog verification/);
  assert.match(report, /Commands passed: 1\/1/);
  assert.match(report, /npm run check: exit 0, 1000ms/);
  assert.match(report, /User Stories/);
  assert.match(report, /release owner.*dashboard health visible/);
  assert.match(report, /Requirement Constraints/);
  assert.match(report, /dense and operational/);
  assert.match(report, /Workspace packages: apps\/web \(@acme\/web\)/);
  assert.match(report, /Acceptance Criteria/);
  assert.match(report, /Dashboard renders release health/);
  assert.match(report, /Acceptance Evidence/);
  assert.match(report, /AC1: Dashboard renders release health/);
  assert.match(report, /AC2: Keep last known dashboard values during background refresh/);
  assert.match(report, /Evidence: Source-changing execution recorded 1 entry touching `src\/App\.tsx`, `src\/ObsoletePanel\.tsx`/);
  assert.match(
    report,
    /Evidence: API state requirement matches this criterion \(api:38\): Keep last known dashboard values during background refresh\./
  );
  assert.match(report, /Evidence: Verification passed: `npm run check` exit 0/);
  assert.match(report, /Evidence: Visual verification failed: 1 screenshot\(s\), 1\/1 required text checks found/);
  assert.match(report, /Status: needs attention/);
  assert.match(report, /Known gap: 1 open question\(s\) remain/);
  assert.match(report, /Assumption: Delivery-level evidence applies to this criterion/);
  assert.match(report, /Manual QA: Exercise the user path for "Dashboard renders release health\." in the implemented UI/);
  assert.match(report, /UI State Checklist/);
  assert.match(report, /\[state\] Line 10: Loading state uses skeleton table rows/);
  assert.match(report, /\[responsive\] Line 14: Tablet layout keeps the KPI strip above the table/);
  assert.match(report, /Design Assets/);
  assert.match(report, /assets\/dashboard\.svg/);
  assert.match(report, /Dimensions: 960x640/);
  assert.match(report, /ViewBox: 0 0 960 640/);
  assert.match(report, /Colors: #f8fafc, #0f172a, rgb\(34, 197, 94\)/);
  assert.match(report, /Text snippets: Release health; Deploy confidence/);
  assert.match(report, /Design Tokens/);
  assert.match(report, /\[color\] Primary color: #2563eb \(ui:18\)/);
  assert.match(report, /API Contracts/);
  assert.match(report, /GET \/api\/dashboard/);
  assert.match(report, /Parameters: query range \(optional, default 7d\)/);
  assert.match(report, /API Data Models/);
  assert.match(report, /dashboard.*releaseHealth, deployConfidence/);
  assert.match(report, /API Error Cases/);
  assert.match(report, /Dashboard endpoint unavailable/);
  assert.match(report, /API Auth Requirements/);
  assert.match(report, /Bearer token is required/);
  assert.match(report, /API State Requirements/);
  assert.match(report, /Keep last known dashboard values during background refresh/);
  assert.match(report, /T03-code-implementation: applied/);
  assert.match(report, /Files touched: `src\/App\.tsx`/);
  assert.match(report, /Written operations: 1/);
  assert.match(report, /Deleted operations: 1/);
  assert.match(report, /Backups recorded: 1/);
  assert.match(report, /replace `src\/App\.tsx`: written, 2048 bytes, 1 replacements, lines 80->86 \(\+6\)/);
  assert.match(report, /delete `src\/ObsoletePanel\.tsx`: deleted, 0 bytes, lines 24->0 \(-24\)/);
  assert.match(report, /Frameworks: React/);
  assert.match(report, /Source Context Sampling/);
  assert.match(report, /Sampling runs recorded: 1/);
  assert.match(report, /dry-run T03-code-implementation, unit U07 \[frontend-route\] Route path \/dashboard/);
  assert.match(report, /`src\/App\.tsx` \(file\)/);
  assert.match(report, /`src\/pages\/Dashboard\.tsx` \(missing\)/);
  assert.match(report, /Omitted: src\/legacy\.tsx \(entry limit reached\)/);
  assert.match(report, /Status: failed/);
  assert.match(report, /desktop 1440x1000/);
  assert.match(report, /!\[desktop screenshot\]\(\.devflow\/artifacts\/visual\/desktop\.png\)/);
  assert.match(report, /blank: no, distinct pixels: 25\.00%/);
  assert.match(report, /Layout desktop overlap at button\.primary <-> span\.badge: Elements overlap by 120px\^2 \(30% of the smaller element\)\. Text: "Deploy \/ Blocked"/);
  assert.match(report, /Risk Assessment/);
  assert.match(report, /\[high\] requirements:8: Requirement contains an unresolved placeholder/);
  assert.match(report, /\[medium\] ui: UI checklist does not include responsive behavior/);
  assert.match(report, /Delivery Readiness/);
  assert.match(report, /Status: needs attention/);
  assert.match(report, /Evidence: 2 acceptance criteria recorded/);
  assert.match(report, /Evidence: 1 medium delivery risk\(s\) recorded for review/);
  assert.match(report, /Attention: 1 high delivery risk\(s\) remain/);
  assert.match(report, /Attention: Visual verification status is failed/);
  assert.match(report, /Attention: 1 open question\(s\) remain/);
  assert.match(report, /Confirm empty state copy/);
});

test("formatDeliveryReport surfaces acceptance evidence gaps when delivery artifacts are missing", () => {
  const report = formatDeliveryReport({
    brief: {
      ...brief,
      acceptanceCriteria: [
        "Checkout handles API errors.",
        "The deployment table includes service, owner, environment, status, build, and next action.",
        "The app builds with `npm run build`."
      ],
      openQuestions: []
    },
    implementationPlanPath: ".devflow/artifacts/implementation-plan.md",
    projectBriefPath: ".devflow/artifacts/project-brief.json",
    taskPlanPath: ".devflow/artifacts/tasks.json",
    taskPlanMarkdownPath: ".devflow/artifacts/tasks.md",
    patchProposalsDir: ".devflow/artifacts/patch-proposals",
    executionLogPath: ".devflow/artifacts/execution-log.json",
    executionLog: undefined,
    rollbackReportPath: ".devflow/artifacts/rollback-report.json",
    verificationReportPath: ".devflow/artifacts/verification-report.json",
    verification: undefined,
    visualReportPath: ".devflow/artifacts/visual/visual-report.json",
    visualReport: undefined
  });

  assert.match(report, /AC1: Checkout handles API errors/);
  assert.match(report, /Status: needs evidence/);
  assert.match(report, /Known gap: No source-changing execution log is available for this delivery/);
  assert.match(report, /Known gap: Verification has not been run/);
  assert.match(report, /Known gap: Visual verification has not been run for a preview URL/);
  assert.match(report, /Known gap: No verification, visual, or applied-change evidence was found/);
  assert.match(report, /Manual QA: Exercise the user path for "Checkout handles API errors\." in the implemented UI/);
  assert.match(report, /AC2: The deployment table includes service, owner, environment, status, build, and next action/);
  assert.match(report, /Manual QA: Exercise the user path for "The deployment table includes service, owner, environment, status, build, and next action\." in the implemented UI/);
  assert.match(report, /AC3: The app builds with `npm run build`/);
  assert.match(report, /Manual QA: Review verification output for "The app builds with `npm run build`\." and rerun the matching command before handoff/);
});

test("formatDeliveryReport includes verification failure output excerpts", () => {
  const failedVerification: VerificationReport = {
    startedAt: "2026-01-01T00:00:00.000Z",
    finishedAt: "2026-01-01T00:00:01.000Z",
    status: "failed",
    results: [
      {
        command: "npm run check",
        exitCode: 1,
        durationMs: 1000,
        stdout: "",
        stderr: "Build failed\nMissing export",
        outputExcerpt: {
          stderr: "Build failed\nMissing export",
          truncatedStderr: true
        }
      }
    ]
  };
  const report = formatDeliveryReport({
    brief: undefined,
    implementationPlanPath: ".devflow/artifacts/implementation-plan.md",
    projectBriefPath: ".devflow/artifacts/project-brief.json",
    taskPlanPath: ".devflow/artifacts/tasks.json",
    taskPlanMarkdownPath: ".devflow/artifacts/tasks.md",
    patchProposalsDir: ".devflow/artifacts/patch-proposals",
    executionLogPath: ".devflow/artifacts/execution-log.json",
    executionLog: undefined,
    rollbackReportPath: ".devflow/artifacts/rollback-report.json",
    verificationReportPath: ".devflow/artifacts/verification-report.json",
    verification: failedVerification,
    visualReportPath: ".devflow/artifacts/visual/visual-report.json",
    visualReport: undefined
  });

  assert.match(report, /Failure output for `npm run check`/);
  assert.match(report, /Build failed/);
  assert.match(report, /Missing export/);
  assert.match(report, /Output excerpt was truncated/);
  assert.match(report, /Suggested follow-up for `npm run check`: Fix missing imports, exports, or module paths/);
  assert.match(report, /Remediation plan/);
  assert.match(report, /Inspect the first unresolved module, export, or import path/);
  assert.match(report, /Related artifacts/);
  assert.match(report, /Full verification report: `\.devflow\/artifacts\/verification-report\.json`/);
});

test("createDeliveryManifest summarizes artifact status and delivery evidence", () => {
  const manifest = createDeliveryManifest({
    brief,
    artifactsDir: ".devflow/artifacts",
    generatedAt: "2026-01-01T00:00:02.000Z",
    deliveryReportPath: ".devflow/artifacts/delivery-report.md",
    deliveryManifestPath: ".devflow/artifacts/delivery-manifest.json",
    implementationPlanPath: ".devflow/artifacts/implementation-plan.md",
    projectBriefPath: ".devflow/artifacts/project-brief.json",
    taskPlanPath: ".devflow/artifacts/tasks.json",
    taskPlanMarkdownPath: ".devflow/artifacts/tasks.md",
    patchProposalsDir: ".devflow/artifacts/patch-proposals",
    sourceContextSummaryPath: ".devflow/artifacts/source-context-summary.json",
    sourceContextSummary: {
      version: 1,
      entries: [
        {
          generatedAt: "2026-01-01T00:00:00.250Z",
          mode: "apply",
          taskId: "T03-code-implementation",
          entries: [{ kind: "file", path: "src/App.tsx", sizeBytes: 2048, truncated: false }],
          omitted: [],
          limits: {
            maxEntries: 14,
            maxFileBytes: 12_000,
            maxTotalBytes: 48_000,
            maxDirectoryEntries: 30
          }
        }
      ]
    },
    executionLogPath: ".devflow/artifacts/execution-log.json",
    taskChangelogPath: ".devflow/artifacts/task-changelog.md",
    taskChangelog,
    executionLog: {
      version: 1,
      entries: [
        {
          taskId: "T03-code-implementation",
          summary: "Apply dashboard source changes.",
          appliedAt: "2026-01-01T00:00:00.500Z",
          status: "applied",
          backupManifestPath: ".devflow/artifacts/backups/backup/manifest.json",
          operations: [
            {
              type: "replace",
              path: "src/App.tsx",
              status: "written",
              bytesWritten: 2048,
              replacements: 1,
              linesBefore: 80,
              linesAfter: 86,
              lineDelta: 6
            },
            {
              type: "delete",
              path: "src/ObsoletePanel.tsx",
              status: "deleted",
              bytesWritten: 0,
              linesBefore: 24,
              linesAfter: 0,
              lineDelta: -24
            }
          ]
        }
      ]
    },
    rollbackReportPath: ".devflow/artifacts/rollback-report.json",
    verificationReportPath: ".devflow/artifacts/verification-report.json",
    verification,
    visualReportPath: ".devflow/artifacts/visual/visual-report.json",
    visualReport: {
      startedAt: "2026-01-01T00:00:00.000Z",
      finishedAt: "2026-01-01T00:00:01.000Z",
      url: "http://127.0.0.1:5173",
      status: "failed",
      screenshots: [
        {
          viewport: { name: "desktop", width: 1440, height: 1000 },
          path: ".devflow/artifacts/visual/desktop.png",
          title: "OpsBoard",
          bodyCharacters: 100,
          analysis: {
            width: 1440,
            height: 1000,
            sampledPixels: 720000,
            distinctPixels: 180000,
            distinctPixelRatio: 0.25,
            blank: false
          }
        }
      ],
      layoutIssues: [
        {
          viewport: { name: "desktop", width: 1440, height: 1000 },
          type: "overlap",
          selector: "button.primary <-> span.badge",
          message: "Elements overlap by 120px^2 (30% of the smaller element).",
          text: "Deploy / Blocked"
        }
      ],
      requiredText: [{ text: "OpsBoard", found: true }]
    },
    artifacts: [
      {
        id: "project-brief",
        label: "Project brief",
        kind: "json",
        path: ".devflow/artifacts/project-brief.json",
        status: "present",
        required: true,
        role: "Structured context."
      },
      {
        id: "visual-screenshot-desktop",
        label: "desktop screenshot",
        kind: "image",
        path: ".devflow/artifacts/visual/desktop.png",
        status: "present",
        required: false,
        role: "Visual evidence."
      }
    ]
  });

  assert.equal(manifest.version, 1);
  assert.equal(manifest.generatedAt, "2026-01-01T00:00:02.000Z");
  assert.equal(manifest.status.readiness, "needs attention");
  assert.equal(manifest.status.verification, "passed");
  assert.equal(manifest.status.visual, "failed");
  assert.equal(manifest.status.sourceChanges, "applied");
  assert.equal(manifest.sourceDocuments?.requirementsPath, "docs/requirements.md");
  assert.equal(manifest.artifacts.length, 2);
  assert.equal(manifest.counts.acceptanceCriteria, 2);
  assert.equal(manifest.counts.highDeliveryRisks, 1);
  assert.equal(manifest.counts.appliedEntries, 1);
  assert.equal(manifest.counts.appliedOperations, 2);
  assert.equal(manifest.counts.touchedFiles, 2);
  assert.equal(manifest.counts.visualScreenshots, 1);
  assert.equal(manifest.counts.visualLayoutIssues, 1);
  assert.equal(manifest.counts.designTokens, 1);
  assert.equal(manifest.counts.apiStateRequirements, 1);
  assert.equal(manifest.counts.reviewerNotes, 2);
  assert.equal(manifest.evidence.acceptanceCriteria[0]?.id, "AC1");
  assert.equal(manifest.evidence.acceptanceCriteria[0]?.status, "needs attention");
  assert.match(manifest.evidence.acceptanceCriteria[0]?.evidence.join("\n") ?? "", /Verification passed/);
  assert.doesNotMatch(
    manifest.evidence.acceptanceCriteria[0]?.evidence.join("\n") ?? "",
    /API (state requirement|error case) matches this criterion/
  );
  assert.match(manifest.evidence.acceptanceCriteria[1]?.evidence.join("\n") ?? "", /API state requirement matches this criterion/);
  assert.deepEqual(manifest.evidence.appliedChanges.operations, {
    total: 2,
    written: 1,
    deleted: 1,
    unchanged: 0
  });
  assert.deepEqual(manifest.evidence.appliedChanges.touchedFiles, ["src/App.tsx", "src/ObsoletePanel.tsx"]);
  assert.equal(manifest.evidence.appliedChanges.lineDelta, -18);
  assert.deepEqual(manifest.evidence.appliedChanges.backupManifestPaths, [".devflow/artifacts/backups/backup/manifest.json"]);
  assert.deepEqual(manifest.evidence.appliedChanges.operationDetails, [
    {
      taskId: "T03-code-implementation",
      summary: "Apply dashboard source changes.",
      appliedAt: "2026-01-01T00:00:00.500Z",
      entryStatus: "applied",
      type: "replace",
      path: "src/App.tsx",
      status: "written",
      bytesWritten: 2048,
      replacements: 1,
      linesBefore: 80,
      linesAfter: 86,
      lineDelta: 6,
      backupManifestPath: ".devflow/artifacts/backups/backup/manifest.json"
    },
    {
      taskId: "T03-code-implementation",
      summary: "Apply dashboard source changes.",
      appliedAt: "2026-01-01T00:00:00.500Z",
      entryStatus: "applied",
      type: "delete",
      path: "src/ObsoletePanel.tsx",
      status: "deleted",
      bytesWritten: 0,
      linesBefore: 24,
      linesAfter: 0,
      lineDelta: -24,
      backupManifestPath: ".devflow/artifacts/backups/backup/manifest.json"
    }
  ]);
  assert.equal(manifest.evidence.visualScreenshots[0]?.blank, false);
  assert.equal(manifest.evidence.visualRequiredText[0]?.found, true);
  assert.deepEqual(manifest.evidence.visualLayoutIssues[0], {
    viewport: "desktop",
    width: 1440,
    height: 1000,
    type: "overlap",
    selector: "button.primary <-> span.badge",
    message: "Elements overlap by 120px^2 (30% of the smaller element).",
    text: "Deploy / Blocked"
  });
  assert.equal(manifest.evidence.designTokens[0]?.name, "Primary color");
  assert.equal(manifest.evidence.designTokens[0]?.value, "#2563eb");
  assert.deepEqual(manifest.evidence.apiStateRequirements, [
    {
      sourceLine: 38,
      summary: "Keep last known dashboard values during background refresh."
    }
  ]);
  assert.equal(manifest.evidence.sourceContext?.[0]?.mode, "apply");
  assert.equal(manifest.evidence.sourceContext?.[0]?.entries[0]?.path, "src/App.tsx");
  assert.equal(manifest.evidence.taskChangelog?.reviewHandoff.reviewerNotes[1], "Reviewer should check generated copy before merge.");
  assert.equal(manifest.evidence.taskChangelog?.verificationSummary?.status, "passed");
  assert.equal(manifest.evidence.deliveryRisks.length, 2);
  assert.deepEqual(manifest.evidence.openQuestions, ["Confirm empty state copy."]);
});

test("createDeliveryManifest includes verification failure output excerpts", () => {
  const failedVerification: VerificationReport = {
    startedAt: "2026-01-01T00:00:00.000Z",
    finishedAt: "2026-01-01T00:00:01.000Z",
    status: "failed",
    results: [
      {
        command: "npm run check",
        exitCode: 1,
        durationMs: 1000,
        stdout: "",
        stderr: "Missing export",
        outputExcerpt: {
          stderr: "Missing export"
        }
      }
    ]
  };
  const manifest = createDeliveryManifest({
    brief: undefined,
    artifactsDir: ".devflow/artifacts",
    generatedAt: "2026-01-01T00:00:02.000Z",
    deliveryReportPath: ".devflow/artifacts/delivery-report.md",
    deliveryManifestPath: ".devflow/artifacts/delivery-manifest.json",
    implementationPlanPath: ".devflow/artifacts/implementation-plan.md",
    projectBriefPath: ".devflow/artifacts/project-brief.json",
    taskPlanPath: ".devflow/artifacts/tasks.json",
    taskPlanMarkdownPath: ".devflow/artifacts/tasks.md",
    patchProposalsDir: ".devflow/artifacts/patch-proposals",
    executionLogPath: ".devflow/artifacts/execution-log.json",
    executionLog: undefined,
    rollbackReportPath: ".devflow/artifacts/rollback-report.json",
    verificationReportPath: ".devflow/artifacts/verification-report.json",
    verification: failedVerification,
    visualReportPath: ".devflow/artifacts/visual/visual-report.json",
    visualReport: undefined,
    artifacts: []
  });

  assert.equal(manifest.evidence.verificationCommands[0]?.outputExcerpt?.stderr, "Missing export");
  assert.equal(
    manifest.evidence.verificationCommands[0]?.remediation,
    "Fix missing imports, exports, or module paths, then rerun the failing verification command."
  );
  assert.equal(manifest.evidence.verificationCommands[0]?.remediationPlan?.category, "imports");
  assert.match(
    manifest.evidence.verificationCommands[0]?.remediationPlan?.nextActions[0] ?? "",
    /Inspect the first unresolved module/
  );
  assert.deepEqual(manifest.evidence.verificationCommands[0]?.remediationPlan?.artifactReferences, [
    {
      label: "Full verification report",
      path: ".devflow/artifacts/verification-report.json"
    }
  ]);
});
